from typing import Protocol, Any


class IRecursoFacultad(Protocol):
    def agregar_laboratorio(self) -> Any: ...
    def agregar_computadoras(self, cantidad: int) -> Any: ...


class IFacultadInfo(Protocol):
    def obtener_info(self) -> str: ...


class IProcesoAdmision(Protocol):
    def iniciar_proceso(self, fecha_inicio: str | None = None, comentario: str | None = None) -> Any: ...
    def finalizar_proceso(self) -> Any: ...
    def obtener_info(self) -> str: ...


class IAuthProvider(Protocol):
    def authenticate(self, usuario_codigo: str, credentials: dict) -> bool: ...


class ICalendarService(Protocol):
    def is_active(self, periodo_codigo: str, fecha: str) -> bool: ...
